### ISSUE TITLE
setup.py for Windows

### ISSUE THREAD

**Issue by wizardCMU** [RaphaelOlivier/robust_speech#4]
I got the following error while installing the package:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 9931: illegal multibyte sequence

Guess we need to change the line 13 to:
with open("README.md", encoding='utf-8') as f:

**Comment by RaphaelOlivier** [comment]
I do not observe that error. Which OS/configuration are you using?

**Comment by wizardCMU** [comment]
Sorry for the typo in the title (now updated). I'm using Windows.

**Comment by RaphaelOlivier** [comment]
Since your fix seems to works fine I have pushed it.
