### ISSUE TITLE
How can I download data files, CommonVoice etc..

### ISSUE THREAD

**Issue by kyoungmingo** [RaphaelOlivier/robust_speech#7]
"We also provide data preparation and loading functions for the LibriSpeech, CommonVoice and SpeechCommands datasets, based on SpeechBrain recipes." in your git.

But, When I run the code according to the Recipe you shared, the following error appears.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/35245580/204545565-7067c6d2-3832-4ad0-b8cd-0981cbb9be37.png">

How can I download data files??

**Comment by RaphaelOlivier** [comment]
Hi,
The recipes can load the local dataset, but not download it (except Speech command). You have to do that manually, and unpack them in your data folder.

**Comment by kyoungmingo** [comment]
Thank you for answer.

I would like to create an adversarial example through an attack model. Can you provide some samples on how?

**Comment by RaphaelOlivier** [comment]
Applying the recipes - like you were doing - is the right way! All you need is the dataset first.

**Comment by kyoungmingo** [comment]
Thank you..

I looked at several python codes and it seems to be explained in detail very well.

**Comment by kyoungmingo** [comment]
Hello~

I want to test using transformer model with cw algorithm.

When I used "python fit_attacker.py attack_configs/LibriSpeech/universal/ctc_5000bpe_fit.yaml", I met this error
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/35245580/205430099-95dd9736-65a9-47f4-966f-069a56f0725b.png">
If possible, can you tell me how to use the CW algorithm attack method using the transformer model in this git,robust_speech?

**Comment by RaphaelOlivier** [comment]
Discussion in [#9](https://github.com/RaphaelOlivier/robust_speech/issues/9) for the last question
