### ISSUE TITLE
 I want to test using transformer model with cw algorithm.

### ISSUE THREAD

**Issue by kyoungmingo** [RaphaelOlivier/robust_speech#9]
Hello~

I want to test using transformer model with cw algorithm.

When I used "python fit_attacker.py attack_configs/LibriSpeech/universal/ctc_5000bpe_fit.yaml", I met this error
image
If possible, can you tell me how to use the CW algorithm attack method using the transformer model in this git,robust_speech?

**Comment by RaphaelOlivier** [comment]
I cannot see the image, so I'm not certain. However, an error would occur if you try to use fit_attacker.py with a CW config. fit_attacker.py is only required for specific attacks that need training, like Universal. Just use evaluate.py directly with one of the /cw/ configs. If you want to compute the adversarial examples once and save them, it's not fit_attacker.py you should use but the save_audio parameter in the attack config.

**Comment by RaphaelOlivier** [comment]
Presumably fixed by answerabove
